name: fpm_cli
description: A command line tool for managing Flutter projects.
executables:
  fpm: fpm
version: 1.1.3
repository: https://github.com/Abduakrim/fpm_cli

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  path: ^1.8.0
  hive: ^2.2.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
