name: fpm_cli
description: A command line tool for managing Flutter projects.
executables:
  fpm: fpm
version: 1.0.0
repository: https://github.com/Abduakrim/fpm_cli

environment:
  sdk: ^3.7.2

dependencies:
  path: ^1.8.0
  ansicolor: ^2.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
